### ISSUE TITLE
Suggestion, activation in specific rounds and other stuff

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2mg#1]
I know that this addon maybe is still work in progress, and maybe these things are already in your TODO list, but I have some things that I suggest to you.

~~It would be nice if you could choose a specific round in which you want to automatically start the event, for example only the last round, or just only the "x" round on the map, something like this~~ (Done with https://github.com/TTT-2/ttt2mg/commit/ea0429f1ace0a3417d6daf0a4637f01520dc952a)

~~Also, I noticed one thing about hardcore minigames, if you use ttt_radio commands "example: I'm with <player>" you can easily see who is in front of you, the solutions could be two or put the disguiser at all for the whole round or deactivate for the whole round the ttt_radio commands~~ (Fixed with https://github.com/TTT-2/ttt2mg/commit/92793dc5c5ae4d9d013dc108c345fab2414b05e8)

**Comment by Alf21** [comment]
Thanks for your feedback. This is really important in the current state :)
I've linked a Trello page with all the planed or done things. If you wanna get an invitation, send me your name or e-mail on Discord and I'll add you :)

That's a nice idea, thought about randomness and other things. Gonna take it into the list 👍 

Thanks for the bug report!
