### ISSUE TITLE
Some issue with forceminigame and with last round of the map

### ISSUE THREAD

**Issue by ThePlatinumGhost** [TTT-2/ttt2mg#3]
**1)**
Forceminigame commands doesn't work if the ttt2_minigames_autostart_random is not set to 100%

How to reproduce

0. set ttt2_minigames_autostart_rounds = "0" 
1. set ttt2_minigames_autostart_random "1" --set to a low number
2. use ulx forceminigame "name" 

the minigame should not force the next round

thats because the forceminigame is affected by ttt2_minigames_autostart_random,
forceminigames should ignore ttt2_minigames_autostart_random and force the game even if the radommess is 1% 
basically the choose minigame should start 100% 

as temporary solution in order to works when i need to force a minigames 
I must
1. set ttt2_minigames_autostart_random "100" --so a game will 100% starts
2. use ulx forceminigame "name" --choose the minigame
3. after the minigame is started set ttt2_minigames_autostart_random "x" back to original value that I put on my server

**2)**
When i use ulx silent forceminigames is not silent and it appears to other player

**3)**
Some minigames have some problem if the minigames is starts last round of the map,
thats because function MINIGAME:OnDeactivation() is called (i think), in the preparing round of the next round, and last round of the map do not have preparing round after the round is finisced, so
should better set MINIGAME:OnDeactivation() called on the postround
it would fix this issue with last map rounds

**Comment by Alf21** [comment]
Is there any "bug" or not intended behavior still left after those fixes? If so, please list them, you were right with your issues. 2. Should be fixed / removed, because there just should be an announcement to the player that triggered the event - theoretically (so no need making it silent).

**Comment by ThePlatinumGhost** [comment]
in fact I closed it because everything that interested me in this post was fixed
